
package com.example.demo.wsdl;

import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-19T11:33:02.291-06:00
 * Generated source version: 3.2.2
 *
 */
public final class CountriesPort_CountriesPortSoap12_Client {

	private static final QName SERVICE_NAME = new QName("http://spring.io/guides/gs-producing-web-service", "CountriesPortService");

    public CountriesPort_CountriesPortSoap12_Client() {
    }

    public Country getCountry(String name) {
        URL wsdlURL = CountriesPortService.WSDL_LOCATION;
        CountriesPortService ss = new CountriesPortService(wsdlURL, SERVICE_NAME);
        CountriesPort port = ss.getCountriesPortSoap12();
        GetCountryRequest _getCountry_getCountryRequest = new GetCountryRequest();
        _getCountry_getCountryRequest.setName(name);
        GetCountryResponse _getCountry__return = port.getCountry(_getCountry_getCountryRequest);
        return _getCountry__return.getCountry();
    }

}
