
package com.example.demo.wsdl;

import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-16T15:17:45.595-06:00
 * Generated source version: 3.2.2
 *
 */
public final class CountriesPort_CountriesPortSoap11_Client {

	private static final QName SERVICE_NAME = new QName("http://spring.io/guides/gs-producing-web-service", "CountriesPortService");
    
	/**
	 * Obtiene un país en base a su nombre desde un servicio SOAP
	 * 
	 * @param name
	 * @return
	 */
    public Country getCountry(String name) {
    	URL wsdlURL = CountriesPortService.WSDL_LOCATION;
    	CountriesPortService ss = new CountriesPortService(wsdlURL, SERVICE_NAME);
    	CountriesPort port = ss.getCountriesPortSoap11();
    	GetCountryRequest _getCountry_getCountryRequest = new GetCountryRequest();
        _getCountry_getCountryRequest.setName(name);
        GetCountryResponse _getCountry__return = port.getCountry(_getCountry_getCountryRequest);
        return _getCountry__return.getCountry();
    }

}
